### PR TITLE
Update constants.js

### PR DESCRIPTION
**Pull request by LBegnaud**
Not sure why, but i found a handful of scripts with this separate value for function disabled. Most of my scripts use your value, but in my code I setup a failback when doing a lookup and had ~10 scripts using this value to denote a disabled function

### CODE REVIEW

**Comment by k-grube** [comment]
It could possibly be a bitflag instead of a simple ID, what OS filter is applied on those function steps?

**Comment by LBegnaud** [comment]
function disabled

Perhaps they had an OS filter before disabling? I can test

**Comment by LBegnaud** [comment]
that's what it is. The script retains the OS filter history when disabling a function

**Comment by LBegnaud** [comment]
negative OSLimit value implies function is disabled

add 2147483648 to get the positive value that correspond with the OS before disabling the function

**Pull request closed without merging**
